version = 1

[[annotations]]
path = ["**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 PLLDN contributors"
SPDX-License-Identifier = "EUPL-1.2"

[[annotations]]
path = ["LICENSE"]
precedence = "override"
SPDX-FileCopyrightText = "European Union"
SPDX-License-Identifier = "EUPL-1.2"
