// SPDX-FileCopyrightText: 2026 PLLDN contributors
// SPDX-License-Identifier: EUPL-1.2
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Ajv2020 } from "ajv/dist/2020.js";
import * as standaloneModule from "ajv/dist/standalone/index.js";
import formats from "ajv-formats";
import { asObject, parseStrictJson } from "../src/validation/json.ts";

const repoRoot = fileURLToPath(new URL("../", import.meta.url));
const schemaNames = [
  "common",
  "project-facts",
  "entity",
  "dimension",
  "source",
  "claim",
  "relation",
  "rule",
  "review",
  "snapshot",
  "decision-trace",
  "text-rule-set",
] as const;

const evaluationTimeSchemaId =
  "https://plldn.invalid/schemas/evaluation-time.schema.json";
function schema(name: (typeof schemaNames)[number]): Record<string, unknown> {
  return asObject(
    parseStrictJson(
      readFileSync(resolve(repoRoot, `schemas/${name}.schema.json`), "utf8"),
    ),
  );
}

export function generateStandaloneValidators(): string {
  const ajv = new Ajv2020({
    strict: true,
    allErrors: true,
    coerceTypes: false,
    useDefaults: false,
    removeAdditional: false,
    code: { source: true, esm: false, lines: true },
  });
  formats.default(ajv);
  for (const name of schemaNames) ajv.addSchema(schema(name));
  ajv.addSchema({
    $id: evaluationTimeSchemaId,
    type: "string",
    format: "date-time",
  });

  const refs: Record<string, string> = {};
  for (const name of schemaNames) {
    if (name === "common") continue;
    refs[name.replaceAll("-", "_")] =
      `https://plldn.invalid/schemas/${name}.schema.json`;
  }
  refs.evaluation_time = evaluationTimeSchemaId;
  const generated = standaloneModule.default.default(ajv, refs);
  const header =
    "// SPDX-FileCopyrightText: 2026 PLLDN contributors\n" +
    "// SPDX-License-Identifier: EUPL-1.2\n" +
    "// GENERATED by tools/generate-standalone-validators.ts; do not edit.\n";
  return `${header}${generated}`;
}

const invoked = process.argv[1] ? resolve(process.argv[1]) : "";
if (invoked === fileURLToPath(import.meta.url)) {
  const output =
    process.argv[2] ??
    resolve(repoRoot, "src/validation/generated/validators.cjs");
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, generateStandaloneValidators());
}
