// SPDX-FileCopyrightText: 2026 PLLDN contributors
// SPDX-License-Identifier: EUPL-1.2
import type { ProductModel } from "./types.ts";

export const PRODUCT_MODEL: ProductModel = {
  languages: [
  {
    entity_id: "language.ada",
    label: "Ada",
    tagline: "Assurance-first systems language with a long life in high-integrity software.",
    categories: ["assurance","system"],
    build_path: ".adb → GNAT/toolchain → native executable",
    good_for: ["high-integrity systems","embedded systems","long-lived codebases"],
    watch_for: ["smaller general-purpose ecosystem","tooling familiarity varies by team"],
  },
  {
    entity_id: "language.bash",
    label: "Bash",
    tagline: "The shortest path from shell command to repeatable Unix automation.",
    categories: ["scripting","tool"],
    build_path: ".sh → shell → script",
    good_for: ["system automation","glue scripts","CI helpers"],
    watch_for: ["portability across shells","large programs become hard to structure"],
  },
  {
    entity_id: "language.c",
    label: "C",
    tagline: "Minimal abstraction between source and machine; still the universal systems interface.",
    categories: ["system","fundament"],
    build_path: ".c → compiler + linker → native executable/library",
    good_for: ["embedded","operating-system interfaces","FFI boundaries"],
    watch_for: ["manual memory safety burden","platform details leak into code"],
  },
  {
    entity_id: "language.cpp",
    label: "C++",
    tagline: "Native performance with a huge language and ecosystem surface.",
    categories: ["system","fundament"],
    build_path: ".cpp → compiler + linker → native executable/library",
    good_for: ["desktop software","engines","performance-critical systems"],
    watch_for: ["complexity and build systems","memory and lifetime hazards remain possible"],
  },
  {
    entity_id: "language.csharp",
    label: "C#",
    tagline: "Managed application language with particularly strong .NET and Windows tooling.",
    categories: ["managed","fundament"],
    build_path: ".cs → dotnet → assembly/native application",
    good_for: ["Windows desktop","services","business applications"],
    watch_for: ["runtime/framework choices matter","less direct for tiny bare-metal targets"],
  },
  {
    entity_id: "language.clojure",
    label: "Clojure",
    tagline: "Functional Lisp on the JVM, optimized for data transformation and interactive development.",
    categories: ["functional","managed"],
    build_path: ".clj → Clojure/JVM → JAR or application",
    good_for: ["data-heavy services","REPL-driven development","JVM integration"],
    watch_for: ["smaller hiring pool","startup and JVM footprint"],
  },
  {
    entity_id: "language.cobol",
    label: "COBOL",
    tagline: "Business-record processing language that remains relevant in large legacy estates.",
    categories: ["legacy","domain"],
    build_path: ".cob → COBOL compiler → native/runtime artifact",
    good_for: ["mainframe business systems","batch processing","legacy maintenance"],
    watch_for: ["modern ecosystem breadth","specialized environment knowledge"],
  },
  {
    entity_id: "language.dart",
    label: "Dart",
    tagline: "Application language centered on Flutter, with native and web compilation paths.",
    categories: ["managed","fundament"],
    build_path: ".dart → Dart/Flutter toolchain → native, JS or Wasm artifact",
    good_for: ["cross-platform UI","mobile apps","Flutter products"],
    watch_for: ["ecosystem is strongly Flutter-shaped","less common outside app development"],
  },
  {
    entity_id: "language.elixir",
    label: "Elixir",
    tagline: "Productive BEAM language built around resilient concurrency.",
    categories: ["managed","functional"],
    build_path: ".ex → BEAM bytecode → release",
    good_for: ["concurrent services","realtime systems","fault-tolerant backends"],
    watch_for: ["BEAM ecosystem is specialized","CPU-heavy native workloads need other tools"],
  },
  {
    entity_id: "language.erlang",
    label: "Erlang",
    tagline: "The original BEAM language for distributed, fault-tolerant systems.",
    categories: ["managed","functional"],
    build_path: ".erl → BEAM bytecode → release",
    good_for: ["telecom-style concurrency","distributed systems","high-uptime services"],
    watch_for: ["syntax and ecosystem are specialized","not aimed at native desktop software"],
  },
  {
    entity_id: "language.fsharp",
    label: "F#",
    tagline: "Functional-first .NET language that keeps access to the wider .NET platform.",
    categories: ["functional","managed"],
    build_path: ".fs → dotnet → assembly/native application",
    good_for: ["domain modeling","data processing","typed .NET services"],
    watch_for: ["smaller ecosystem than C#","team familiarity can be a constraint"],
  },
  {
    entity_id: "language.fortran",
    label: "Fortran",
    tagline: "Numerical language whose modern toolchains still matter in HPC and scientific computing.",
    categories: ["science","system"],
    build_path: ".f90 → Fortran compiler → native executable/library",
    good_for: ["HPC","numerical simulation","scientific legacy"],
    watch_for: ["general app ecosystem is narrow","interop/build knowledge can be specialized"],
  },
  {
    entity_id: "language.go",
    label: "Go",
    tagline: "Small language, fast toolchain and simple native deployment for networked software.",
    categories: ["fundament","managed"],
    build_path: ".go → go build → native binary",
    good_for: ["CLI tools","network services","infrastructure software"],
    watch_for: ["GC/runtime trade-offs","language intentionally limits abstraction features"],
  },
  {
    entity_id: "language.haskell",
    label: "Haskell",
    tagline: "Pure functional language with a powerful type system and strong abstraction tools.",
    categories: ["functional","managed"],
    build_path: ".hs → GHC → native executable",
    good_for: ["compilers and DSLs","research-heavy systems","type-driven design"],
    watch_for: ["steep learning curve","ecosystem fit depends strongly on domain"],
  },
  {
    entity_id: "language.java",
    label: "Java",
    tagline: "Mature JVM default for large server and enterprise ecosystems.",
    categories: ["managed","fundament"],
    build_path: ".java → javac → JVM bytecode/JAR",
    good_for: ["enterprise backends","large teams","JVM ecosystems"],
    watch_for: ["runtime footprint","framework stacks can become heavy"],
  },
  {
    entity_id: "language.javascript",
    label: "JavaScript",
    tagline: "The native language of the web platform and a general scripting/runtime language.",
    categories: ["scripting","managed"],
    build_path: ".js → runtime/bundler → browser bundle or server app",
    good_for: ["browser applications","web tooling","event-driven services"],
    watch_for: ["dynamic typing without extra tooling","ecosystem churn"],
  },
  {
    entity_id: "language.julia",
    label: "Julia",
    tagline: "Dynamic technical-computing language designed for numerical and scientific work.",
    categories: ["science","managed"],
    build_path: ".jl → Julia/JIT → runtime application",
    good_for: ["numerical research","scientific prototyping","data exploration"],
    watch_for: ["startup/runtime deployment","smaller production ecosystem"],
  },
  {
    entity_id: "language.kotlin",
    label: "Kotlin",
    tagline: "Modern multi-target language with deep JVM and Android roots.",
    categories: ["managed","fundament"],
    build_path: ".kt → JVM/Native/JS/Wasm toolchain → target artifact",
    good_for: ["Android","JVM services","multiplatform apps"],
    watch_for: ["multi-target builds add complexity","JVM heritage shapes much of the ecosystem"],
  },
  {
    entity_id: "language.lua",
    label: "Lua",
    tagline: "Tiny embeddable scripting language common inside games and host applications.",
    categories: ["scripting","domain"],
    build_path: ".lua → interpreter/host → script or embedded bytecode",
    good_for: ["embedded scripting","game tooling","configuration"],
    watch_for: ["standard library is intentionally small","large standalone systems need conventions"],
  },
  {
    entity_id: "language.nim",
    label: "Nim",
    tagline: "Compact systems-oriented language with native compilation and a lightweight feel.",
    categories: ["system","fundament"],
    build_path: ".nim → Nim compiler → native or JS artifact",
    good_for: ["small native tools","cross-platform utilities","systems scripting"],
    watch_for: ["smaller ecosystem","fewer battle-tested libraries than mainstream peers"],
  },
  {
    entity_id: "language.objective-c",
    label: "Objective-C",
    tagline: "Dynamic C-family language tied closely to older Apple platform stacks.",
    categories: ["legacy","system"],
    build_path: ".m → Clang → native Apple binary",
    good_for: ["existing Apple codebases","C/Objective-C interop","legacy Cocoa"],
    watch_for: ["Swift is the modern default","platform scope is narrow"],
  },
  {
    entity_id: "language.ocaml",
    label: "OCaml",
    tagline: "Pragmatic ML-family language combining strong typing with native and bytecode builds.",
    categories: ["functional","system"],
    build_path: ".ml → ocamlopt/ocamlc → native or bytecode",
    good_for: ["compilers","static analysis","domain-heavy tooling"],
    watch_for: ["smaller mainstream ecosystem","tooling conventions differ from larger platforms"],
  },
  {
    entity_id: "language.perl",
    label: "Perl",
    tagline: "Text-processing workhorse with a large legacy footprint in Unix automation.",
    categories: ["scripting","legacy"],
    build_path: ".pl → Perl → script",
    good_for: ["text processing","legacy automation","quick system glue"],
    watch_for: ["modern adoption is limited","maintainability depends heavily on style"],
  },
  {
    entity_id: "language.php",
    label: "PHP",
    tagline: "Web-focused runtime with an enormous deployment footprint.",
    categories: ["managed","fundament"],
    build_path: ".php → PHP runtime → web/server application",
    good_for: ["web backends","CMS ecosystems","shared hosting"],
    watch_for: ["web-centric design","large systems depend heavily on framework discipline"],
  },
  {
    entity_id: "language.powershell",
    label: "PowerShell",
    tagline: "Object-oriented shell and automation language designed around administration workflows.",
    categories: ["scripting","tool"],
    build_path: ".ps1 → PowerShell → script/module",
    good_for: ["Windows automation","administration","cross-platform operations"],
    watch_for: ["not a native application language","host/version differences matter"],
  },
  {
    entity_id: "language.python",
    label: "Python",
    tagline: "General-purpose scripting language with exceptional tooling, data and automation reach.",
    categories: ["scripting","fundament"],
    build_path: ".py → Python/packager → script, wheel or bundled app",
    good_for: ["automation","data work","prototyping"],
    watch_for: ["runtime packaging","CPU-bound performance and threading constraints"],
  },
  {
    entity_id: "language.r",
    label: "R",
    tagline: "Statistics-first environment with a deep analysis and visualization ecosystem.",
    categories: ["science","domain"],
    build_path: ".R → R → script/package",
    good_for: ["statistics","research analysis","visualization"],
    watch_for: ["application deployment is secondary","general software engineering ergonomics vary"],
  },
  {
    entity_id: "language.ruby",
    label: "Ruby",
    tagline: "Dynamic language optimized for developer expressiveness and web application productivity.",
    categories: ["scripting","managed"],
    build_path: ".rb → Ruby → script/gem/application",
    good_for: ["web applications","automation","DSL-heavy tooling"],
    watch_for: ["runtime performance","smaller modern footprint than its peak"],
  },
  {
    entity_id: "language.rust",
    label: "Rust",
    tagline: "Native systems language centered on memory safety without garbage collection.",
    categories: ["system","fundament"],
    build_path: ".rs → cargo/rustc → native or Wasm binary",
    good_for: ["systems tools","security-sensitive software","native services"],
    watch_for: ["ownership learning curve","compile times and ecosystem complexity can grow"],
  },
  {
    entity_id: "language.scala",
    label: "Scala",
    tagline: "JVM language mixing object-oriented and functional styles with a powerful type system.",
    categories: ["functional","managed"],
    build_path: ".scala → Scala toolchain → JVM, JS or native artifact",
    good_for: ["JVM data systems","typed backends","functional architectures"],
    watch_for: ["language/tooling complexity","build times and version ecosystems"],
  },
  {
    entity_id: "language.solidity",
    label: "Solidity",
    tagline: "Domain language for EVM smart contracts.",
    categories: ["domain"],
    build_path: ".sol → solc → EVM bytecode + ABI",
    good_for: ["Ethereum-compatible contracts","on-chain protocols","EVM tooling"],
    watch_for: ["security mistakes are expensive","not a general-purpose application language"],
  },
  {
    entity_id: "language.swift",
    label: "Swift",
    tagline: "Modern native language for Apple platforms with expanding server and embedded reach.",
    categories: ["system","fundament"],
    build_path: ".swift → Swift compiler → native or Wasm artifact",
    good_for: ["Apple apps","native libraries","modern systems code"],
    watch_for: ["best tooling remains Apple-centric","cross-platform ecosystem is smaller"],
  },
  {
    entity_id: "language.typescript",
    label: "TypeScript",
    tagline: "JavaScript with a static analysis layer for larger codebases and tooling.",
    categories: ["managed","fundament"],
    build_path: ".ts → tsc/bundler → JavaScript/bundle",
    good_for: ["web applications","Node services","large JS codebases"],
    watch_for: ["still inherits JS runtime behavior","build/tooling stacks can sprawl"],
  },
  {
    entity_id: "language.visual-basic-dotnet",
    label: "Visual Basic .NET",
    tagline: "Readable .NET language still useful in existing business and desktop estates.",
    categories: ["managed","legacy"],
    build_path: ".vb → dotnet → assembly/application",
    good_for: ["existing .NET business software","Windows desktop","maintenance"],
    watch_for: ["new ecosystem energy is concentrated on C#","cross-platform examples are scarcer"],
  },
  {
    entity_id: "language.zig",
    label: "Zig",
    tagline: "Low-level language and toolchain focused on explicit control and cross-compilation.",
    categories: ["system","fundament"],
    build_path: ".zig → zig build → native or Wasm binary",
    good_for: ["native utilities","embedded work","cross-compilation"],
    watch_for: ["young ecosystem and language evolution","manual memory management remains explicit"],
  },
  ],
  licenses: [
  {
    entity_id: "license.0bsd",
    label: "0BSD",
    family: "permissive",
    tagline: "Near-zero-condition permissive licensing.",
    good_when: "maximize reuse with almost no downstream friction",
    watch_for: "very little control over downstream proprietary reuse",
  },
  {
    entity_id: "license.agpl-3.0-only",
    label: "AGPL-3.0-only",
    family: "network-copyleft",
    tagline: "Strong network copyleft fixed to AGPL v3.",
    good_when: "require source-sharing obligations to reach network service use",
    watch_for: "high integration friction for proprietary service stacks",
  },
  {
    entity_id: "license.agpl-3.0-or-later",
    label: "AGPL-3.0-or-later",
    family: "network-copyleft",
    tagline: "Network copyleft with an upgrade path to later AGPL versions.",
    good_when: "keep service-side modifications in the copyleft commons",
    watch_for: "future-version option changes the long-term license surface",
  },
  {
    entity_id: "license.apache-2.0",
    label: "Apache-2.0",
    family: "permissive",
    tagline: "Permissive licensing with an express patent grant.",
    good_when: "broad commercial reuse where patent language matters",
    watch_for: "notice and modification-marking obligations still need compliance",
  },
  {
    entity_id: "license.bsd-3-clause",
    label: "BSD-3-Clause",
    family: "permissive",
    tagline: "Classic permissive license with attribution and non-endorsement language.",
    good_when: "simple reusable libraries and tools",
    watch_for: "downstream proprietary closure remains allowed",
  },
  {
    entity_id: "license.cc0-1.0",
    label: "CC0-1.0",
    family: "public-domain-like",
    tagline: "Public-domain dedication with a fallback license structure.",
    good_when: "maximize reuse of data, examples or simple material",
    watch_for: "software patent and jurisdiction questions deserve separate review",
  },
  {
    entity_id: "license.eupl-1.2",
    label: "EUPL-1.2",
    family: "strong-copyleft",
    tagline: "EU-oriented strong copyleft license with compatibility provisions.",
    good_when: "open-source projects that want a European legal frame",
    watch_for: "compatibility and redistribution paths should be checked case by case",
  },
  {
    entity_id: "license.gpl-2.0-only",
    label: "GPL-2.0-only",
    family: "strong-copyleft",
    tagline: "Strong copyleft locked to GPL version 2.",
    good_when: "keep distributed derivatives under GPLv2",
    watch_for: "version lock and compatibility constraints matter",
  },
  {
    entity_id: "license.gpl-2.0-or-later",
    label: "GPL-2.0-or-later",
    family: "strong-copyleft",
    tagline: "GPLv2 strong copyleft with permission to use later GPL versions.",
    good_when: "retain copyleft while allowing later-version migration",
    watch_for: "downstream may choose a later GPL version",
  },
  {
    entity_id: "license.gpl-3.0-only",
    label: "GPL-3.0-only",
    family: "strong-copyleft",
    tagline: "Strong copyleft with GPLv3's additional patent and anti-tivoization terms.",
    good_when: "ensure distributed derivatives remain under GPLv3",
    watch_for: "proprietary linking and some ecosystem combinations are difficult",
  },
  {
    entity_id: "license.gpl-3.0-or-later",
    label: "GPL-3.0-or-later",
    family: "strong-copyleft",
    tagline: "GPLv3 strong copyleft with a later-version option.",
    good_when: "strong copyleft with forward-version flexibility",
    watch_for: "future GPL versions can become selectable downstream",
  },
  {
    entity_id: "license.lgpl-3.0-only",
    label: "LGPL-3.0-only",
    family: "weak-copyleft",
    tagline: "Library-oriented weak copyleft fixed to LGPLv3.",
    good_when: "keep a library open while permitting broader application use",
    watch_for: "relinking and modification obligations still require care",
  },
  {
    entity_id: "license.lgpl-3.0-or-later",
    label: "LGPL-3.0-or-later",
    family: "weak-copyleft",
    tagline: "LGPLv3 weak copyleft with a later-version option.",
    good_when: "open libraries intended for use by proprietary applications",
    watch_for: "later-version option and relinking duties affect compliance",
  },
  {
    entity_id: "license.mit",
    label: "MIT",
    family: "permissive",
    tagline: "Short permissive license centered on preserving notice and permission text.",
    good_when: "maximize adoption and commercial reuse",
    watch_for: "others may close modified or combined downstream products",
  },
  {
    entity_id: "license.mpl-2.0",
    label: "MPL-2.0",
    family: "weak-copyleft",
    tagline: "File-level weak copyleft designed to mix with larger proprietary works.",
    good_when: "keep modified MPL-covered files open without forcing the whole application open",
    watch_for: "file boundaries and notice obligations matter",
  },
  ],
  use_cases: [
  {
    use_case_id: "windows-cli",
    label: "Windows CLI tool",
    question: "Ship a compact command-line tool on Windows.",
    language_ids: ["language.go","language.rust","language.zig","language.nim"],
    rationale: "Favor simple native deployment and predictable packaging.",
  },
  {
    use_case_id: "windows-gui",
    label: "Windows desktop GUI",
    question: "Build a native-feeling Windows desktop application.",
    language_ids: ["language.csharp","language.cpp","language.rust"],
    rationale: "Start with the platform UI stack, then trade portability against native integration.",
  },
  {
    use_case_id: "automation",
    label: "Automation and admin tooling",
    question: "Automate machines, files, services or developer workflows.",
    language_ids: ["language.powershell","language.python","language.bash"],
    rationale: "Time-to-result and host integration matter more than language purity.",
  },
  {
    use_case_id: "network-security",
    label: "Network or security tool",
    question: "Build network-facing infrastructure or security tooling.",
    language_ids: ["language.go","language.rust","language.zig"],
    rationale: "Prefer explicit deployment, strong networking support and a small operational footprint.",
  },
  {
    use_case_id: "data-forensics",
    label: "Data analysis or forensics",
    question: "Explore, transform and inspect large or messy datasets.",
    language_ids: ["language.python","language.r","language.julia"],
    rationale: "Library ecosystems usually dominate the choice.",
  },
  {
    use_case_id: "safety-critical",
    label: "High-assurance software",
    question: "Build software where failure has unusually high consequences.",
    language_ids: ["language.ada","language.rust"],
    rationale: "Assurance evidence, analyzability and memory-safety strategy outrank convenience.",
  },
  {
    use_case_id: "embedded",
    label: "Embedded or microcontroller",
    question: "Run close to the hardware with tight resource budgets.",
    language_ids: ["language.c","language.cpp","language.rust","language.zig"],
    rationale: "Target support, footprint and hardware access are first-class constraints.",
  },
  {
    use_case_id: "high-performance",
    label: "High-performance compute",
    question: "Maximize native numerical or systems performance.",
    language_ids: ["language.cpp","language.rust","language.zig","language.fortran"],
    rationale: "Benchmark the actual workload; toolchain and library fit matter as much as syntax.",
  },
  {
    use_case_id: "web-backend",
    label: "Web backend",
    question: "Build APIs, services or server-side applications.",
    language_ids: ["language.go","language.typescript","language.python","language.elixir","language.java","language.csharp"],
    rationale: "Choose around concurrency, ecosystem, deployment and team constraints.",
  },
  {
    use_case_id: "web-frontend",
    label: "Web frontend",
    question: "Build browser-delivered user interfaces.",
    language_ids: ["language.typescript","language.javascript","language.dart"],
    rationale: "Browser platform fit and framework/tooling ecosystem dominate.",
  },
  {
    use_case_id: "mobile",
    label: "Mobile application",
    question: "Target modern phone and tablet platforms.",
    language_ids: ["language.kotlin","language.swift","language.dart","language.csharp"],
    rationale: "Native platform integration versus shared code is the core trade-off.",
  },
  {
    use_case_id: "enterprise",
    label: "Enterprise application",
    question: "Build long-lived business software with large-team tooling.",
    language_ids: ["language.java","language.csharp","language.kotlin","language.scala"],
    rationale: "Ecosystem stability, tooling and maintainability usually outweigh novelty.",
  },
  {
    use_case_id: "reverse-engineering",
    label: "Reverse engineering tooling",
    question: "Inspect binaries, protocols and machine-level behavior.",
    language_ids: ["language.c","language.python","language.rust"],
    rationale: "You need both low-level visibility and fast scripting for glue and analysis.",
  },
  {
    use_case_id: "prototype",
    label: "Fast prototype",
    question: "Get from idea to working experiment with minimal ceremony.",
    language_ids: ["language.python","language.bash","language.ruby","language.javascript"],
    rationale: "Optimize for feedback speed, then harden the parts that survive.",
  },
  {
    use_case_id: "blockchain",
    label: "EVM smart contract",
    question: "Build contracts for Ethereum-compatible chains.",
    language_ids: ["language.solidity"],
    rationale: "The execution environment dictates the domain language and security model.",
  },
  ],
};

export const PRODUCT_COMPARE_DIMENSIONS = [
  "dimension.type-checking-model",
  "dimension.execution-model",
  "dimension.memory-management-model",
  "dimension.runtime-targets",
  "dimension.concurrency-models",
  "dimension.c-ffi-support",
  "dimension.bare-metal-support",
  "dimension.webassembly-support",
  "dimension.package-dependency-tools",
] as const;
