// SPDX-FileCopyrightText: 2026 PLLDN contributors
// SPDX-License-Identifier: EUPL-1.2
import type { LanguageDecisionProfile } from "./types.ts";

export const LANGUAGE_DECISION_PROFILES: Readonly<
  Record<string, LanguageDecisionProfile>
> = {
  "language.ada": {
    performance: {
      throughput_potential: "high",
      startup: "fast",
      runtime_overhead: "low",
      latency_predictability: "high",
      build_speed: "medium",
    },
    complexity: {
      learning_curve: "high",
      language_surface: "medium",
      memory_reasoning: "medium",
      toolchain: "medium",
      dependency_management: "medium",
      deployment: "low",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "niche",
      tooling: "strong",
      hiring_pool: "niche",
    },
  },
  "language.bash": {
    performance: {
      throughput_potential: "low",
      startup: "fast",
      runtime_overhead: "medium",
      latency_predictability: "low",
      build_speed: "fast",
    },
    complexity: {
      learning_curve: "low",
      language_surface: "medium",
      memory_reasoning: "low",
      toolchain: "low",
      dependency_management: "low",
      deployment: "low",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "broad",
      tooling: "good",
      hiring_pool: "broad",
    },
  },
  "language.c": {
    performance: {
      throughput_potential: "high",
      startup: "fast",
      runtime_overhead: "low",
      latency_predictability: "high",
      build_speed: "fast",
    },
    complexity: {
      learning_curve: "medium",
      language_surface: "medium",
      memory_reasoning: "high",
      toolchain: "medium",
      dependency_management: "medium",
      deployment: "low",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "broad",
      tooling: "strong",
      hiring_pool: "broad",
    },
  },
  "language.cpp": {
    performance: {
      throughput_potential: "high",
      startup: "fast",
      runtime_overhead: "low",
      latency_predictability: "high",
      build_speed: "slow",
    },
    complexity: {
      learning_curve: "high",
      language_surface: "high",
      memory_reasoning: "high",
      toolchain: "high",
      dependency_management: "high",
      deployment: "medium",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "broad",
      tooling: "strong",
      hiring_pool: "broad",
    },
  },
  "language.csharp": {
    performance: {
      throughput_potential: "high",
      startup: "medium",
      runtime_overhead: "medium",
      latency_predictability: "medium",
      build_speed: "medium",
    },
    complexity: {
      learning_curve: "low",
      language_surface: "medium",
      memory_reasoning: "low",
      toolchain: "low",
      dependency_management: "low",
      deployment: "low",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "broad",
      tooling: "strong",
      hiring_pool: "broad",
    },
  },
  "language.clojure": {
    performance: {
      throughput_potential: "medium",
      startup: "slow",
      runtime_overhead: "high",
      latency_predictability: "low",
      build_speed: "slow",
    },
    complexity: {
      learning_curve: "high",
      language_surface: "medium",
      memory_reasoning: "low",
      toolchain: "medium",
      dependency_management: "medium",
      deployment: "medium",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "moderate",
      tooling: "good",
      hiring_pool: "niche",
    },
  },
  "language.cobol": {
    performance: {
      throughput_potential: "medium",
      startup: "fast",
      runtime_overhead: "low",
      latency_predictability: "high",
      build_speed: "medium",
    },
    complexity: {
      learning_curve: "medium",
      language_surface: "medium",
      memory_reasoning: "medium",
      toolchain: "high",
      dependency_management: "medium",
      deployment: "high",
    },
    ecosystem: {
      maturity: "legacy-stable",
      breadth: "niche",
      tooling: "good",
      hiring_pool: "niche",
    },
  },
  "language.dart": {
    performance: {
      throughput_potential: "high",
      startup: "medium",
      runtime_overhead: "medium",
      latency_predictability: "medium",
      build_speed: "medium",
    },
    complexity: {
      learning_curve: "low",
      language_surface: "medium",
      memory_reasoning: "low",
      toolchain: "medium",
      dependency_management: "low",
      deployment: "medium",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "moderate",
      tooling: "strong",
      hiring_pool: "moderate",
    },
  },
  "language.elixir": {
    performance: {
      throughput_potential: "medium",
      startup: "medium",
      runtime_overhead: "high",
      latency_predictability: "medium",
      build_speed: "medium",
    },
    complexity: {
      learning_curve: "medium",
      language_surface: "medium",
      memory_reasoning: "low",
      toolchain: "medium",
      dependency_management: "low",
      deployment: "medium",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "moderate",
      tooling: "good",
      hiring_pool: "moderate",
    },
  },
  "language.erlang": {
    performance: {
      throughput_potential: "medium",
      startup: "medium",
      runtime_overhead: "high",
      latency_predictability: "medium",
      build_speed: "medium",
    },
    complexity: {
      learning_curve: "medium",
      language_surface: "medium",
      memory_reasoning: "low",
      toolchain: "medium",
      dependency_management: "medium",
      deployment: "medium",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "moderate",
      tooling: "good",
      hiring_pool: "niche",
    },
  },
  "language.fsharp": {
    performance: {
      throughput_potential: "high",
      startup: "medium",
      runtime_overhead: "medium",
      latency_predictability: "medium",
      build_speed: "medium",
    },
    complexity: {
      learning_curve: "medium",
      language_surface: "medium",
      memory_reasoning: "low",
      toolchain: "medium",
      dependency_management: "low",
      deployment: "low",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "moderate",
      tooling: "strong",
      hiring_pool: "niche",
    },
  },
  "language.fortran": {
    performance: {
      throughput_potential: "high",
      startup: "fast",
      runtime_overhead: "low",
      latency_predictability: "high",
      build_speed: "medium",
    },
    complexity: {
      learning_curve: "medium",
      language_surface: "medium",
      memory_reasoning: "medium",
      toolchain: "medium",
      dependency_management: "medium",
      deployment: "medium",
    },
    ecosystem: {
      maturity: "legacy-stable",
      breadth: "moderate",
      tooling: "good",
      hiring_pool: "niche",
    },
  },
  "language.go": {
    performance: {
      throughput_potential: "high",
      startup: "fast",
      runtime_overhead: "low",
      latency_predictability: "medium",
      build_speed: "fast",
    },
    complexity: {
      learning_curve: "low",
      language_surface: "low",
      memory_reasoning: "low",
      toolchain: "low",
      dependency_management: "low",
      deployment: "low",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "broad",
      tooling: "strong",
      hiring_pool: "broad",
    },
  },
  "language.haskell": {
    performance: {
      throughput_potential: "high",
      startup: "medium",
      runtime_overhead: "medium",
      latency_predictability: "medium",
      build_speed: "slow",
    },
    complexity: {
      learning_curve: "high",
      language_surface: "high",
      memory_reasoning: "medium",
      toolchain: "high",
      dependency_management: "medium",
      deployment: "medium",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "moderate",
      tooling: "good",
      hiring_pool: "niche",
    },
  },
  "language.java": {
    performance: {
      throughput_potential: "high",
      startup: "slow",
      runtime_overhead: "high",
      latency_predictability: "medium",
      build_speed: "medium",
    },
    complexity: {
      learning_curve: "medium",
      language_surface: "high",
      memory_reasoning: "low",
      toolchain: "medium",
      dependency_management: "medium",
      deployment: "medium",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "broad",
      tooling: "strong",
      hiring_pool: "broad",
    },
  },
  "language.javascript": {
    performance: {
      throughput_potential: "medium",
      startup: "fast",
      runtime_overhead: "medium",
      latency_predictability: "low",
      build_speed: "fast",
    },
    complexity: {
      learning_curve: "low",
      language_surface: "medium",
      memory_reasoning: "low",
      toolchain: "medium",
      dependency_management: "high",
      deployment: "medium",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "broad",
      tooling: "strong",
      hiring_pool: "broad",
    },
  },
  "language.julia": {
    performance: {
      throughput_potential: "high",
      startup: "slow",
      runtime_overhead: "high",
      latency_predictability: "low",
      build_speed: "fast",
    },
    complexity: {
      learning_curve: "low",
      language_surface: "medium",
      memory_reasoning: "low",
      toolchain: "medium",
      dependency_management: "medium",
      deployment: "high",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "moderate",
      tooling: "good",
      hiring_pool: "niche",
    },
  },
  "language.kotlin": {
    performance: {
      throughput_potential: "high",
      startup: "medium",
      runtime_overhead: "medium",
      latency_predictability: "medium",
      build_speed: "medium",
    },
    complexity: {
      learning_curve: "low",
      language_surface: "medium",
      memory_reasoning: "low",
      toolchain: "medium",
      dependency_management: "medium",
      deployment: "medium",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "broad",
      tooling: "strong",
      hiring_pool: "broad",
    },
  },
  "language.lua": {
    performance: {
      throughput_potential: "medium",
      startup: "fast",
      runtime_overhead: "low",
      latency_predictability: "medium",
      build_speed: "fast",
    },
    complexity: {
      learning_curve: "low",
      language_surface: "low",
      memory_reasoning: "low",
      toolchain: "low",
      dependency_management: "medium",
      deployment: "low",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "moderate",
      tooling: "good",
      hiring_pool: "moderate",
    },
  },
  "language.nim": {
    performance: {
      throughput_potential: "high",
      startup: "fast",
      runtime_overhead: "low",
      latency_predictability: "high",
      build_speed: "fast",
    },
    complexity: {
      learning_curve: "medium",
      language_surface: "medium",
      memory_reasoning: "medium",
      toolchain: "medium",
      dependency_management: "medium",
      deployment: "low",
    },
    ecosystem: {
      maturity: "emerging",
      breadth: "niche",
      tooling: "good",
      hiring_pool: "niche",
    },
  },
  "language.objective-c": {
    performance: {
      throughput_potential: "high",
      startup: "fast",
      runtime_overhead: "low",
      latency_predictability: "high",
      build_speed: "medium",
    },
    complexity: {
      learning_curve: "medium",
      language_surface: "high",
      memory_reasoning: "medium",
      toolchain: "medium",
      dependency_management: "medium",
      deployment: "medium",
    },
    ecosystem: {
      maturity: "legacy-stable",
      breadth: "moderate",
      tooling: "strong",
      hiring_pool: "niche",
    },
  },
  "language.ocaml": {
    performance: {
      throughput_potential: "high",
      startup: "fast",
      runtime_overhead: "low",
      latency_predictability: "high",
      build_speed: "fast",
    },
    complexity: {
      learning_curve: "medium",
      language_surface: "medium",
      memory_reasoning: "low",
      toolchain: "medium",
      dependency_management: "medium",
      deployment: "low",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "moderate",
      tooling: "good",
      hiring_pool: "niche",
    },
  },
  "language.perl": {
    performance: {
      throughput_potential: "medium",
      startup: "fast",
      runtime_overhead: "medium",
      latency_predictability: "low",
      build_speed: "fast",
    },
    complexity: {
      learning_curve: "medium",
      language_surface: "high",
      memory_reasoning: "low",
      toolchain: "low",
      dependency_management: "medium",
      deployment: "medium",
    },
    ecosystem: {
      maturity: "legacy-stable",
      breadth: "moderate",
      tooling: "good",
      hiring_pool: "moderate",
    },
  },
  "language.php": {
    performance: {
      throughput_potential: "medium",
      startup: "fast",
      runtime_overhead: "medium",
      latency_predictability: "low",
      build_speed: "fast",
    },
    complexity: {
      learning_curve: "low",
      language_surface: "medium",
      memory_reasoning: "low",
      toolchain: "low",
      dependency_management: "medium",
      deployment: "low",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "broad",
      tooling: "strong",
      hiring_pool: "broad",
    },
  },
  "language.powershell": {
    performance: {
      throughput_potential: "low",
      startup: "slow",
      runtime_overhead: "high",
      latency_predictability: "low",
      build_speed: "fast",
    },
    complexity: {
      learning_curve: "low",
      language_surface: "medium",
      memory_reasoning: "low",
      toolchain: "low",
      dependency_management: "medium",
      deployment: "low",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "broad",
      tooling: "strong",
      hiring_pool: "broad",
    },
  },
  "language.python": {
    performance: {
      throughput_potential: "low",
      startup: "fast",
      runtime_overhead: "medium",
      latency_predictability: "low",
      build_speed: "fast",
    },
    complexity: {
      learning_curve: "low",
      language_surface: "medium",
      memory_reasoning: "low",
      toolchain: "low",
      dependency_management: "medium",
      deployment: "medium",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "broad",
      tooling: "strong",
      hiring_pool: "broad",
    },
  },
  "language.r": {
    performance: {
      throughput_potential: "low",
      startup: "slow",
      runtime_overhead: "high",
      latency_predictability: "low",
      build_speed: "fast",
    },
    complexity: {
      learning_curve: "medium",
      language_surface: "medium",
      memory_reasoning: "low",
      toolchain: "medium",
      dependency_management: "medium",
      deployment: "high",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "broad",
      tooling: "strong",
      hiring_pool: "moderate",
    },
  },
  "language.ruby": {
    performance: {
      throughput_potential: "medium",
      startup: "fast",
      runtime_overhead: "medium",
      latency_predictability: "low",
      build_speed: "fast",
    },
    complexity: {
      learning_curve: "low",
      language_surface: "medium",
      memory_reasoning: "low",
      toolchain: "low",
      dependency_management: "medium",
      deployment: "medium",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "moderate",
      tooling: "good",
      hiring_pool: "moderate",
    },
  },
  "language.rust": {
    performance: {
      throughput_potential: "high",
      startup: "fast",
      runtime_overhead: "low",
      latency_predictability: "high",
      build_speed: "slow",
    },
    complexity: {
      learning_curve: "high",
      language_surface: "medium",
      memory_reasoning: "high",
      toolchain: "medium",
      dependency_management: "medium",
      deployment: "low",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "broad",
      tooling: "strong",
      hiring_pool: "broad",
    },
  },
  "language.scala": {
    performance: {
      throughput_potential: "high",
      startup: "slow",
      runtime_overhead: "high",
      latency_predictability: "medium",
      build_speed: "slow",
    },
    complexity: {
      learning_curve: "high",
      language_surface: "high",
      memory_reasoning: "low",
      toolchain: "high",
      dependency_management: "high",
      deployment: "medium",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "moderate",
      tooling: "good",
      hiring_pool: "moderate",
    },
  },
  "language.solidity": {
    performance: {
      throughput_potential: "medium",
      startup: "fast",
      runtime_overhead: "low",
      latency_predictability: "high",
      build_speed: "medium",
    },
    complexity: {
      learning_curve: "medium",
      language_surface: "medium",
      memory_reasoning: "medium",
      toolchain: "high",
      dependency_management: "high",
      deployment: "high",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "moderate",
      tooling: "good",
      hiring_pool: "moderate",
    },
  },
  "language.swift": {
    performance: {
      throughput_potential: "high",
      startup: "fast",
      runtime_overhead: "low",
      latency_predictability: "high",
      build_speed: "medium",
    },
    complexity: {
      learning_curve: "medium",
      language_surface: "medium",
      memory_reasoning: "medium",
      toolchain: "medium",
      dependency_management: "medium",
      deployment: "low",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "broad",
      tooling: "strong",
      hiring_pool: "broad",
    },
  },
  "language.typescript": {
    performance: {
      throughput_potential: "medium",
      startup: "fast",
      runtime_overhead: "medium",
      latency_predictability: "low",
      build_speed: "fast",
    },
    complexity: {
      learning_curve: "low",
      language_surface: "medium",
      memory_reasoning: "low",
      toolchain: "medium",
      dependency_management: "high",
      deployment: "medium",
    },
    ecosystem: {
      maturity: "mature",
      breadth: "broad",
      tooling: "strong",
      hiring_pool: "broad",
    },
  },
  "language.visual-basic-dotnet": {
    performance: {
      throughput_potential: "high",
      startup: "medium",
      runtime_overhead: "medium",
      latency_predictability: "medium",
      build_speed: "medium",
    },
    complexity: {
      learning_curve: "low",
      language_surface: "medium",
      memory_reasoning: "low",
      toolchain: "low",
      dependency_management: "low",
      deployment: "low",
    },
    ecosystem: {
      maturity: "legacy-stable",
      breadth: "moderate",
      tooling: "strong",
      hiring_pool: "moderate",
    },
  },
  "language.zig": {
    performance: {
      throughput_potential: "high",
      startup: "fast",
      runtime_overhead: "low",
      latency_predictability: "high",
      build_speed: "fast",
    },
    complexity: {
      learning_curve: "medium",
      language_surface: "medium",
      memory_reasoning: "high",
      toolchain: "medium",
      dependency_management: "medium",
      deployment: "low",
    },
    ecosystem: {
      maturity: "emerging",
      breadth: "niche",
      tooling: "good",
      hiring_pool: "niche",
    },
  },
};
