// SPDX-FileCopyrightText: 2026 PLLDN contributors
// SPDX-License-Identifier: EUPL-1.2
import type { LicenseDecisionProfile } from "./types.ts";

export const LICENSE_DECISION_PROFILES: Readonly<
  Record<string, LicenseDecisionProfile>
> = {
  "license.0bsd": {
    model: "open-source",
    osi_status: "approved",
    spdx_id: "0BSD",
    canonical_source: "https://spdx.org/licenses/0BSD.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "yes",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "none",
      notice: "no",
      patent_grant: "no",
      time_rule: "none",
    },
    compliance_complexity: "low",
    business_model_friction: "low",
  },
  "license.agpl-3.0-only": {
    model: "open-source",
    osi_status: "approved",
    spdx_id: "AGPL-3.0-only",
    canonical_source: "https://spdx.org/licenses/AGPL-3.0-only.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "conditional",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "network-service",
      notice: "yes",
      patent_grant: "yes",
      time_rule: "none",
    },
    compliance_complexity: "high",
    business_model_friction: "high",
  },
  "license.agpl-3.0-or-later": {
    model: "open-source",
    osi_status: "approved",
    spdx_id: "AGPL-3.0-or-later",
    canonical_source: "https://spdx.org/licenses/AGPL-3.0-or-later.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "conditional",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "network-service",
      notice: "yes",
      patent_grant: "yes",
      time_rule: "none",
    },
    compliance_complexity: "high",
    business_model_friction: "high",
  },
  "license.apache-2.0": {
    model: "open-source",
    osi_status: "approved",
    spdx_id: "Apache-2.0",
    canonical_source: "https://spdx.org/licenses/Apache-2.0.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "yes",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "none",
      notice: "yes",
      patent_grant: "yes",
      time_rule: "none",
    },
    compliance_complexity: "low",
    business_model_friction: "low",
  },
  "license.bsd-3-clause": {
    model: "open-source",
    osi_status: "approved",
    spdx_id: "BSD-3-Clause",
    canonical_source: "https://spdx.org/licenses/BSD-3-Clause.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "yes",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "none",
      notice: "yes",
      patent_grant: "no",
      time_rule: "none",
    },
    compliance_complexity: "low",
    business_model_friction: "low",
  },
  "license.cc0-1.0": {
    model: "public-domain-like",
    osi_status: "not-approved",
    spdx_id: "CC0-1.0",
    canonical_source: "https://spdx.org/licenses/CC0-1.0.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "yes",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "none",
      notice: "no",
      patent_grant: "no",
      time_rule: "none",
    },
    compliance_complexity: "low",
    business_model_friction: "low",
  },
  "license.eupl-1.2": {
    model: "open-source",
    osi_status: "approved",
    spdx_id: "EUPL-1.2",
    canonical_source: "https://spdx.org/licenses/EUPL-1.2.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "conditional",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "work",
      notice: "yes",
      patent_grant: "yes",
      time_rule: "none",
    },
    compliance_complexity: "high",
    business_model_friction: "medium",
  },
  "license.gpl-2.0-only": {
    model: "open-source",
    osi_status: "approved",
    spdx_id: "GPL-2.0-only",
    canonical_source: "https://spdx.org/licenses/GPL-2.0-only.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "yes",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "work",
      notice: "yes",
      patent_grant: "no",
      time_rule: "none",
    },
    compliance_complexity: "high",
    business_model_friction: "medium",
  },
  "license.gpl-2.0-or-later": {
    model: "open-source",
    osi_status: "approved",
    spdx_id: "GPL-2.0-or-later",
    canonical_source: "https://spdx.org/licenses/GPL-2.0-or-later.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "yes",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "work",
      notice: "yes",
      patent_grant: "no",
      time_rule: "none",
    },
    compliance_complexity: "high",
    business_model_friction: "medium",
  },
  "license.gpl-3.0-only": {
    model: "open-source",
    osi_status: "approved",
    spdx_id: "GPL-3.0-only",
    canonical_source: "https://spdx.org/licenses/GPL-3.0-only.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "yes",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "work",
      notice: "yes",
      patent_grant: "yes",
      time_rule: "none",
    },
    compliance_complexity: "high",
    business_model_friction: "medium",
  },
  "license.gpl-3.0-or-later": {
    model: "open-source",
    osi_status: "approved",
    spdx_id: "GPL-3.0-or-later",
    canonical_source: "https://spdx.org/licenses/GPL-3.0-or-later.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "yes",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "work",
      notice: "yes",
      patent_grant: "yes",
      time_rule: "none",
    },
    compliance_complexity: "high",
    business_model_friction: "medium",
  },
  "license.lgpl-3.0-only": {
    model: "open-source",
    osi_status: "approved",
    spdx_id: "LGPL-3.0-only",
    canonical_source: "https://spdx.org/licenses/LGPL-3.0-only.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "yes",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "library",
      notice: "yes",
      patent_grant: "yes",
      time_rule: "none",
    },
    compliance_complexity: "high",
    business_model_friction: "medium",
  },
  "license.lgpl-3.0-or-later": {
    model: "open-source",
    osi_status: "approved",
    spdx_id: "LGPL-3.0-or-later",
    canonical_source: "https://spdx.org/licenses/LGPL-3.0-or-later.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "yes",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "library",
      notice: "yes",
      patent_grant: "yes",
      time_rule: "none",
    },
    compliance_complexity: "high",
    business_model_friction: "medium",
  },
  "license.mit": {
    model: "open-source",
    osi_status: "approved",
    spdx_id: "MIT",
    canonical_source: "https://spdx.org/licenses/MIT.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "yes",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "none",
      notice: "yes",
      patent_grant: "no",
      time_rule: "none",
    },
    compliance_complexity: "low",
    business_model_friction: "low",
  },
  "license.mpl-2.0": {
    model: "open-source",
    osi_status: "approved",
    spdx_id: "MPL-2.0",
    canonical_source: "https://spdx.org/licenses/MPL-2.0.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "yes",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "file",
      notice: "yes",
      patent_grant: "yes",
      time_rule: "none",
    },
    compliance_complexity: "medium",
    business_model_friction: "low",
  },
  "license.bsd-2-clause": {
    model: "open-source",
    osi_status: "approved",
    spdx_id: "BSD-2-Clause",
    canonical_source: "https://spdx.org/licenses/BSD-2-Clause.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "yes",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "none",
      notice: "yes",
      patent_grant: "no",
      time_rule: "none",
    },
    compliance_complexity: "low",
    business_model_friction: "low",
  },
  "license.isc": {
    model: "open-source",
    osi_status: "approved",
    spdx_id: "ISC",
    canonical_source: "https://spdx.org/licenses/ISC.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "yes",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "none",
      notice: "yes",
      patent_grant: "no",
      time_rule: "none",
    },
    compliance_complexity: "low",
    business_model_friction: "low",
  },
  "license.zlib": {
    model: "open-source",
    osi_status: "approved",
    spdx_id: "Zlib",
    canonical_source: "https://spdx.org/licenses/Zlib.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "yes",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "none",
      notice: "yes",
      patent_grant: "no",
      time_rule: "none",
    },
    compliance_complexity: "low",
    business_model_friction: "low",
  },
  "license.unlicense": {
    model: "public-domain-like",
    osi_status: "approved",
    spdx_id: "Unlicense",
    canonical_source: "https://spdx.org/licenses/Unlicense.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "yes",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "none",
      notice: "no",
      patent_grant: "no",
      time_rule: "none",
    },
    compliance_complexity: "low",
    business_model_friction: "low",
  },
  "license.epl-2.0": {
    model: "open-source",
    osi_status: "approved",
    spdx_id: "EPL-2.0",
    canonical_source: "https://spdx.org/licenses/EPL-2.0.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "yes",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "file",
      notice: "yes",
      patent_grant: "yes",
      time_rule: "none",
    },
    compliance_complexity: "medium",
    business_model_friction: "low",
  },
  "license.cddl-1.0": {
    model: "open-source",
    osi_status: "approved",
    spdx_id: "CDDL-1.0",
    canonical_source: "https://spdx.org/licenses/CDDL-1.0.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "yes",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "file",
      notice: "yes",
      patent_grant: "yes",
      time_rule: "none",
    },
    compliance_complexity: "medium",
    business_model_friction: "low",
  },
  "license.polyform-noncommercial-1.0.0": {
    model: "source-available",
    osi_status: "not-approved",
    spdx_id: "PolyForm-Noncommercial-1.0.0",
    canonical_source:
      "https://polyformproject.org/licenses/noncommercial/1.0.0",
    rights: {
      use: "conditional",
      modify: "conditional",
      redistribute: "conditional",
      commercial_use: "no",
      internal_business_use: "conditional",
      saas_hosting: "conditional",
      competitive_use: "conditional",
    },
    obligations: {
      source_disclosure: "none",
      notice: "yes",
      patent_grant: "yes",
      time_rule: "none",
    },
    compliance_complexity: "medium",
    business_model_friction: "high",
  },
  "license.polyform-perimeter-1.0.1": {
    model: "source-available",
    osi_status: "not-approved",
    spdx_id: null,
    canonical_source: "https://polyformproject.org/licenses/perimeter/1.0.1",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "conditional",
      internal_business_use: "yes",
      saas_hosting: "conditional",
      competitive_use: "no",
    },
    obligations: {
      source_disclosure: "none",
      notice: "yes",
      patent_grant: "yes",
      time_rule: "none",
    },
    compliance_complexity: "medium",
    business_model_friction: "high",
  },
  "license.polyform-shield-1.0.0": {
    model: "source-available",
    osi_status: "not-approved",
    spdx_id: null,
    canonical_source: "https://polyformproject.org/licenses/shield/1.0.0",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "conditional",
      internal_business_use: "yes",
      saas_hosting: "conditional",
      competitive_use: "no",
    },
    obligations: {
      source_disclosure: "none",
      notice: "yes",
      patent_grant: "yes",
      time_rule: "none",
    },
    compliance_complexity: "medium",
    business_model_friction: "high",
  },
  "license.polyform-strict-1.0.0": {
    model: "source-available",
    osi_status: "not-approved",
    spdx_id: null,
    canonical_source: "https://polyformproject.org/licenses/strict/1.0.0",
    rights: {
      use: "conditional",
      modify: "no",
      redistribute: "no",
      commercial_use: "no",
      internal_business_use: "conditional",
      saas_hosting: "no",
      competitive_use: "conditional",
    },
    obligations: {
      source_disclosure: "none",
      notice: "no",
      patent_grant: "yes",
      time_rule: "none",
    },
    compliance_complexity: "medium",
    business_model_friction: "high",
  },
  "license.polyform-internal-use-1.0.0": {
    model: "source-available",
    osi_status: "not-approved",
    spdx_id: null,
    canonical_source: "https://polyformproject.org/licenses/internal-use/1.0.0",
    rights: {
      use: "conditional",
      modify: "yes",
      redistribute: "no",
      commercial_use: "conditional",
      internal_business_use: "yes",
      saas_hosting: "no",
      competitive_use: "conditional",
    },
    obligations: {
      source_disclosure: "none",
      notice: "no",
      patent_grant: "yes",
      time_rule: "none",
    },
    compliance_complexity: "medium",
    business_model_friction: "high",
  },
  "license.polyform-small-business-1.0.0": {
    model: "source-available",
    osi_status: "not-approved",
    spdx_id: "PolyForm-Small-Business-1.0.0",
    canonical_source:
      "https://polyformproject.org/licenses/small-business/1.0.0",
    rights: {
      use: "conditional",
      modify: "conditional",
      redistribute: "conditional",
      commercial_use: "conditional",
      internal_business_use: "conditional",
      saas_hosting: "conditional",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "none",
      notice: "yes",
      patent_grant: "yes",
      time_rule: "none",
    },
    compliance_complexity: "medium",
    business_model_friction: "medium",
  },
  "license.polyform-free-trial-1.0.0": {
    model: "source-available",
    osi_status: "not-approved",
    spdx_id: null,
    canonical_source: "https://polyformproject.org/licenses/free-trial/1.0.0",
    rights: {
      use: "conditional",
      modify: "yes",
      redistribute: "no",
      commercial_use: "conditional",
      internal_business_use: "conditional",
      saas_hosting: "no",
      competitive_use: "conditional",
    },
    obligations: {
      source_disclosure: "none",
      notice: "no",
      patent_grant: "yes",
      time_rule: "trial",
    },
    compliance_complexity: "medium",
    business_model_friction: "high",
  },
  "license.polyform-countdown-1.0.0": {
    model: "license-transition",
    osi_status: "not-applicable",
    spdx_id: null,
    canonical_source: "https://polyformproject.org/licenses/countdown/1.0.0",
    rights: {
      use: "unknown",
      modify: "unknown",
      redistribute: "unknown",
      commercial_use: "unknown",
      internal_business_use: "unknown",
      saas_hosting: "unknown",
      competitive_use: "unknown",
    },
    obligations: {
      source_disclosure: "unknown",
      notice: "unknown",
      patent_grant: "unknown",
      time_rule: "change-date",
    },
    compliance_complexity: "high",
    business_model_friction: "medium",
  },
  "license.busl-1.1": {
    model: "source-available",
    osi_status: "not-approved",
    spdx_id: "BUSL-1.1",
    canonical_source: "https://mariadb.com/bsl11/",
    rights: {
      use: "conditional",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "conditional",
      internal_business_use: "conditional",
      saas_hosting: "conditional",
      competitive_use: "conditional",
    },
    obligations: {
      source_disclosure: "none",
      notice: "yes",
      patent_grant: "no",
      time_rule: "change-date",
    },
    compliance_complexity: "high",
    business_model_friction: "high",
  },
  "license.elastic-2.0": {
    model: "source-available",
    osi_status: "not-approved",
    spdx_id: "Elastic-2.0",
    canonical_source: "https://www.elastic.co/licensing/elastic-license",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "conditional",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "none",
      notice: "yes",
      patent_grant: "yes",
      time_rule: "none",
    },
    compliance_complexity: "medium",
    business_model_friction: "medium",
  },
  "license.sspl-1.0": {
    model: "source-available",
    osi_status: "not-approved",
    spdx_id: "SSPL-1.0",
    canonical_source: "https://spdx.org/licenses/SSPL-1.0.html",
    rights: {
      use: "yes",
      modify: "yes",
      redistribute: "yes",
      commercial_use: "yes",
      internal_business_use: "yes",
      saas_hosting: "conditional",
      competitive_use: "yes",
    },
    obligations: {
      source_disclosure: "network-service",
      notice: "yes",
      patent_grant: "yes",
      time_rule: "none",
    },
    compliance_complexity: "high",
    business_model_friction: "high",
  },
};
